### PR TITLE
Revert "Docs Update: Adding Reown as one of the available wallet tools on Polygon"

### PR DESCRIPTION
**Pull request by fukinbubba**
Reverts 0xPolygon/polygon-docs#2519

### CODE REVIEW

**Comment by fukinbubba** [comment]
k

**Review by fukinbubba — COMMENTED** [review]
k

**Review by fukinbubba — COMMENTED** [review]
kurtosis run --enclave cdk --args-file "https://raw.githubusercontent.com/0xPolygon/kurtosis-cdk/refs/heads/main/.github/tests/fork12-pessimistic.yml" github.com/0xPolygon/kurtosis-cdk

**Review by fukinbubba — COMMENTED** [review]
k

**Review by FKNCOIN — COMMENTED** [review]
Pulled

**Review by FKNCOIN — COMMENTED** [review]
K

**Pull request closed without merging**
